set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM ${CMAKE_SYSTEM_NAME})
if(CMAKE_SYSTEM_VERSION)
  set(CMAKE_SYSTEM ${CMAKE_SYSTEM}-${CMAKE_SYSTEM_VERSION})
endif()

if(CMAKE_TOOLCHAIN_REMOVE_MPATH)
	list(REMOVE_ITEM CMAKE_MODULE_PATH ${CMAKE_TOOLCHAIN_REMOVE_MPATH})
	unset(CMAKE_TOOLCHAIN_REMOVE_MPATH)
endif()

include(Platform/Linux)

# remove bad or redundant entries from Platform/UnixPaths.cmake
set_property(GLOBAL PROPERTY FIND_LIBRARY_USE_LIB32_PATHS FALSE)
set_property(GLOBAL PROPERTY FIND_LIBRARY_USE_LIBX32_PATHS FALSE)
set_property(GLOBAL PROPERTY FIND_LIBRARY_USE_LIB64_PATHS FALSE)

list(REMOVE_ITEM CMAKE_SYSTEM_PREFIX_PATH /usr/X11R6 /usr/pkg /opt)
list(REMOVE_DUPLICATES CMAKE_SYSTEM_PREFIX_PATH)
list(REMOVE_ITEM CMAKE_SYSTEM_INCLUDE_PATH /usr/include/X11)
list(REMOVE_ITEM CMAKE_SYSTEM_LIBRARY_PATH /usr/lib/X11)
