: << 'EOF'
CT_CMAKE_SYS_KERNEL: Should be one of Linux, Window, Darwin or Generic
CT_CMAKE_SYSTEM_PROCESSOR: Research
EOF

# get the relative path back to prefix dir
toolchainbackpath=$(echo "${scriptsubdir}" | sed 's,//*[^/][^/]*,/..,g')

# Todo: map these to cmake systems
CT_CMAKE_SYSTEM_NAME=Generic
case ${CT_TARGET_KERNEL} in
  [Ll]inux) CT_CMAKE_SYSTEM_NAME=Linux;;
esac
CT_CMAKE_SYSTEM_PROCESSOR=${CT_TARGET_ARCH}
CT_CMAKE_SYSTEM_VERSION=${CT_LINUX_VERSION:-1}
CT_CMAKE_SYSTEM_PLATFORM_NAME=

# CT_ARCH_ENDIAN

CT_CMAKE_SYSROOT_SUBDIR=${CT_SYSROOT_DIR#${CT_PREFIX_DIR}}
CT_CMAKE_C_COMPILER_PATH=bin/${CT_TARGET}-gcc
CT_CMAKE_CXX_COMPILER_PATH=bin/${CT_TARGET}-g++
CT_CMAKE_Fortran_COMPILER_PATH=bin/${CT_TARGET}-gfortran
CT_CMAKE_OBJC_COMPILER_PATH=bin/${CT_TARGET}-gobjc
CT_CMAKE_OBJCXX_COMPILER_PATH=bin/${CT_TARGET}-gobjc++

if [ "${CT_CMAKE_SYSTEM_NAME}" = "Linux" ]; then
  CT_CMAKE_SYSTEM_PLATFORM_NAME=${CT_CMAKE_SYSTEM_NAME}_Crosstool
  mkdir -p "${CT_PREFIX_DIR}/${scriptsubdir}/Platform"
  cat << 'EOF' > "${CT_PREFIX_DIR}/${scriptsubdir}/Platform/${CT_CMAKE_SYSTEM_PLATFORM_NAME}.cmake"
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM ${CMAKE_SYSTEM_NAME})
if(CMAKE_SYSTEM_VERSION)
  set(CMAKE_SYSTEM ${CMAKE_SYSTEM}-${CMAKE_SYSTEM_VERSION})
endif()

if(CMAKE_TOOLCHAIN_REMOVE_MPATH)
  list(REMOVE_ITEM CMAKE_MODULE_PATH ${CMAKE_TOOLCHAIN_REMOVE_MPATH})
  unset(CMAKE_TOOLCHAIN_REMOVE_MPATH)
endif()

include(Platform/Linux)

# remove bad or redundant entries from Platform/UnixPaths.cmake
set_property(GLOBAL PROPERTY FIND_LIBRARY_USE_LIB32_PATHS FALSE)
set_property(GLOBAL PROPERTY FIND_LIBRARY_USE_LIBX32_PATHS FALSE)
set_property(GLOBAL PROPERTY FIND_LIBRARY_USE_LIB64_PATHS FALSE)

list(REMOVE_ITEM CMAKE_SYSTEM_PREFIX_PATH /usr/X11R6 /usr/pkg /opt)
list(REMOVE_DUPLICATES CMAKE_SYSTEM_PREFIX_PATH)
list(REMOVE_ITEM CMAKE_SYSTEM_INCLUDE_PATH /usr/include/X11)
list(REMOVE_ITEM CMAKE_SYSTEM_LIBRARY_PATH /usr/lib/X11)
EOF
fi

cat << EOF
# CMake toolchain file

# Allow relocation of the toolchain, PACKAGE_PREFIX_DIR
# should point to the root installation (CT prefix path during build)
get_filename_component(PACKAGE_PREFIX_DIR "\${CMAKE_CURRENT_LIST_DIR}${toolchainbackpath}" ABSOLUTE)
EOF

if [ -n "${CT_CMAKE_SYSTEM_PLATFORM_NAME}" ]; then
  cat << EOF
list(APPEND CMAKE_MODULE_PATH \${CMAKE_CURRENT_LIST_DIR})
set(CMAKE_TOOLCHAIN_REMOVE_MPATH \${CMAKE_CURRENT_LIST_DIR})

EOF
fi

cat << EOF
set(CMAKE_SYSTEM_NAME ${CT_CMAKE_SYSTEM_PLATFORM_NAME:-${CT_CMAKE_SYSTEM_NAME}})
set(CMAKE_SYSTEM_PROCESSOR ${CT_CMAKE_SYSTEM_PROCESSOR})
set(CMAKE_SYSTEM_VERSION ${CT_CMAKE_SYSTEM_VERSION})

set(CMAKE_INSTALL_SO_NO_EXE 0)

# Generic paths and search settings
set(CMAKE_PROGRAM_PATH "\${PACKAGE_PREFIX_DIR}/bin")
set(CMAKE_SYSROOT "\${PACKAGE_PREFIX_DIR}${CT_CMAKE_SYSROOT_SUBDIR}")
set(CMAKE_FIND_ROOT_PATH "\${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(ENV{PKG_CONFIG_PATH} "")
set(ENV{PKG_CONFIG_LIBDIR} "\${CMAKE_SYSROOT}/usr/lib/pkgconfig:\${CMAKE_SYSROOT}/usr/share/pkgconfig")
set(ENV{PKG_CONFIG_SYSROOT_DIR} "\${CMAKE_SYSROOT}")

# Compiler binaries
set(CMAKE_C_COMPILER "\${PACKAGE_PREFIX_DIR}/${CT_CMAKE_C_COMPILER_PATH}")
set(CMAKE_CXX_COMPILER "\${PACKAGE_PREFIX_DIR}/${CT_CMAKE_CXX_COMPILER_PATH}")
set(CMAKE_Fortran_COMPILER "\${PACKAGE_PREFIX_DIR}/${CT_CMAKE_Fortran_COMPILER_PATH}")
set(CMAKE_OBJC_COMPILER "\${PACKAGE_PREFIX_DIR}/${CT_CMAKE_OBJC_COMPILER_PATH}")
set(CMAKE_OBJCXX_COMPILER "\${PACKAGE_PREFIX_DIR}/${CT_CMAKE_OBJCXX_COMPILER_PATH}")

# Defaults are fitting for Debug and Release builds
# Remaining settings can be seeded by using the *_INIT variables
# The *_INIT variables have been around forever, even if they are
# only documented since 3.7

# TODO: potentially set global Makros via add_definitions, much cleaner
# these might require generator expressions for the various languages

# set(CMAKE_C_FLAGS_INIT "@@CT_CMAKE_TARGET_CFLAGS@@")
# set(CMAKE_CXX_FLAGS_INIT "@@CT_CMAKE_TARGET_CXXFLAGS@@")
# set(CMAKE_EXE_LINKER_FLAGS_INIT "@@CT_CMAKE_TARGET_LDFLAGS@@")
# set(CMAKE_SHARED_LINKER_FLAGS_INIT "@@CT_CMAKE_TARGET_LDFLAGS@@")
# set(CMAKE_MODULE_LINKER_FLAGS_INIT "@@CT_CMAKE_TARGET_LDFLAGS@@")
EOF
